In [132]:
%pylab

import math
import numpy as np
import matplotlib.pyplot as plt
import skimage.transform as sktr
import skimage as sk
import skimage.io as skio
from skimage.transform import rescale
import math
from skimage import filters
import scipy as sp
from skimage.draw import polygon
from scipy.interpolate import RectBivariateSpline, interp2d
from numpy.linalg import inv
from scipy.spatial import Delaunay
import os

def get_points(im1, im2,num_points=36):
    print('Please select 2 points in each image for alignment.')
    plt.imshow(im1)
    x = plt.ginput(num_points, timeout=200)
    plt.close()
    plt.imshow(im2)
    y = plt.ginput(num_points, timeout=200)
    plt.close()
    return (x,y)

# high sf
# im2 = skio.imread('george_small.jpg')/255
# print(np.shape(im2))
# # low sf
# im = skio.imread('eric_small.jpg')/255
# im1 = sp.misc.imresize(im, np.shape(im2))/255
# x,y = get_points(im1, im2)
# print(x)
# print("====================================")
# print(y)



Using matplotlib backend: TkAgg
Populating the interactive namespace from numpy and matplotlib


In [ ]:
# im2 = skio.imread('george_small.jpg')/255


In [ ]:
# x2 = [(54.37187119353564, 187.56292782514709), (114.84640326648253, 78.194093225136839), (222.92854569472797, 22.866329839249261), (382.47837499356655, 34.446559385132673), (458.39321312769135, 106.50132100396297), (491.84720959357679, 192.70969651220639), (135.43347801471975, 639.19188011460142), (72.385561598243214, 545.26335157576898), (58.23194770883012, 423.02759525811041), (71.098869426478387, 289.21160939456843), (119.99317195354183, 175.98269827926367), (219.06846917943352, 129.66178009572991), (360.60460807356452, 136.09524095455401), (446.81298358180783, 209.43669474514911), (476.40690353239887, 321.37891368868907), (490.56051742181199, 448.76143869340694), (454.53313661239685, 561.9903498087117), (379.90499065003684, 644.33864880166061), (249.94908130178936, 717.68010259225582), (85.25248331589151, 312.37206848633525), (145.72701538883837, 277.63137984868501), (229.36200655355213, 299.50514676868704), (347.7376863559162, 307.22529979927594), (395.34529671121476, 287.92491722280363), (463.53998181475066, 321.37891368868907), (171.4608588241349, 352.25952581104491), (376.04491413474244, 361.26637101339873), (202.34147094649074, 473.20858995693868), (278.25630908061555, 356.11960232633942), (341.30422549709209, 480.92874298752764), (280.8296934241452, 455.19489955223111), (184.32778054178317, 576.14396369812482), (269.24946387826174, 551.69681243459308), (350.31107069944591, 587.72419324400835), (310.42361337473619, 605.73788364871587), (237.0821595841411, 607.02457582048066)]
# y2 = [(65.401792072157605, 180.16528771489618), (111.17846970262113, 60.637296124241402), (202.73182496354818, 9.7743209792819243), (379.48066359228233, 12.317469736529915), (455.77512630972149, 88.611932453969075), (535.88431216303275, 204.32520090875187), (190.01608117730834, 657.00567969889119), (123.89421348886103, 567.99547319521207), (109.90689532399713, 480.25684107015701), (97.191151537757293, 334.0257875283985), (137.88153165372486, 154.73380014241638), (239.60748194364382, 101.32767624020892), (379.48066359228233, 100.05610186158492), (465.94772133871345, 159.82009765691237), (493.92235766844112, 328.93949001390263), (493.92235766844112, 490.42943609914892), (473.57716761045731, 573.08177070970805), (415.08474619375397, 643.01836153402735), (296.82832898172319, 684.98031602861886), (121.35106473161304, 331.4826387711505), (167.12774236207653, 275.53336611169516), (259.95267200162755, 295.87855616967897), (359.13547353429851, 297.15013054830297), (429.07206435861781, 272.99021735444717), (468.49087009596144, 322.58161812078265), (200.18867620630019, 328.93949001390263), (398.55427927164214, 326.39634125665464), (243.42220507951575, 444.65275846868536), (298.09990336034718, 322.58161812078265), (347.69130412668267, 447.19590722593335), (294.2851802244752, 454.82535349767727), (210.36127123529209, 546.37870875860426), (289.19888270997933, 533.66296497236453), (379.48066359228233, 541.29241124410839), (346.41972974805867, 564.1807500593402), (287.92730833135533, 574.35334508833205)]

In [ ]:
# x2+= [(0.0,0.0), (float(len(im2[0])),0), (float(len(im2[0])), float(len(im2))),(0.0, float(len(im2)))]

# y2+= [(0.0,0.0), (float(len(im2[0])),0), (float(len(im2[0])), float(len(im2))),(0.0, float(len(im2)))]

In [ ]:
# print x2

In [ ]:
# x2 = [(54.37187119353564, 187.56292782514709), (114.84640326648253, 78.19409322513684), (222.92854569472797, 22.86632983924926), (382.47837499356655, 34.44655938513267), (458.39321312769135, 106.50132100396297), (491.8472095935768, 192.7096965122064), (135.43347801471975, 639.1918801146014), (72.38556159824321, 545.263351575769), (58.23194770883012, 423.0275952581104), (71.09886942647839, 289.2116093945684), (119.99317195354183, 175.98269827926367), (219.06846917943352, 129.6617800957299), (360.6046080735645, 136.09524095455401), (446.8129835818078, 209.4366947451491), (476.40690353239887, 321.37891368868907), (490.560517421812, 448.76143869340694), (454.53313661239685, 561.9903498087117), (379.90499065003684, 644.3386488016606), (249.94908130178936, 717.6801025922558), (85.25248331589151, 312.37206848633525), (145.72701538883837, 277.631379848685), (229.36200655355213, 299.50514676868704), (347.7376863559162, 307.22529979927594), (395.34529671121476, 287.92491722280363), (463.53998181475066, 321.37891368868907), (171.4608588241349, 352.2595258110449), (376.04491413474244, 361.2663710133987), (202.34147094649074, 473.2085899569387), (278.25630908061555, 356.1196023263394), (341.3042254970921, 480.92874298752764), (280.8296934241452, 455.1948995522311), (184.32778054178317, 576.1439636981248), (269.24946387826174, 551.6968124345931), (350.3110706994459, 587.7241932440083), (310.4236133747362, 605.7378836487159), (237.0821595841411, 607.0245758204807), (0.0, 0.0), (602.0, 0), (602.0, 750.0), (0.0, 650.0), (0.0, 0.0), (602.0, 0), (602.0, 750.0), (0.0, 750.0)]

In [ ]:
# y2 = [(65.4017920721576, 180.16528771489618), (111.17846970262113, 60.6372961242414), (202.73182496354818, 9.774320979281924), (379.4806635922823, 12.317469736529915), (455.7751263097215, 88.61193245396908), (535.8843121630327, 204.32520090875187), (190.01608117730834, 657.0056796988912), (123.89421348886103, 567.9954731952121), (109.90689532399713, 480.256841070157), (97.19115153775729, 334.0257875283985), (137.88153165372486, 154.73380014241638), (239.60748194364382, 101.32767624020892), (379.4806635922823, 100.05610186158492), (465.94772133871345, 159.82009765691237), (493.9223576684411, 328.9394900139026), (493.9223576684411, 490.4294360991489), (473.5771676104573, 573.081770709708), (415.084746193754, 643.0183615340273), (296.8283289817232, 684.9803160286189), (121.35106473161304, 331.4826387711505), (167.12774236207653, 275.53336611169516), (259.95267200162755, 295.878556169679), (359.1354735342985, 297.15013054830297), (429.0720643586178, 272.99021735444717), (468.49087009596144, 322.58161812078265), (200.1886762063002, 328.9394900139026), (398.55427927164214, 326.39634125665464), (243.42220507951575, 444.65275846868536), (298.0999033603472, 322.58161812078265), (347.69130412668267, 447.19590722593335), (294.2851802244752, 454.82535349767727), (210.3612712352921, 546.3787087586043), (289.19888270997933, 533.6629649723645), (379.4806635922823, 541.2924112441084), (346.41972974805867, 564.1807500593402), (287.92730833135533, 574.353345088332), (0.0, 0.0), (602.0, 0), (602.0, 750.0), (0.0, 750.0), (0.0, 0.0), (602.0, 0), (602.0, 750.0), (0.0, 750.0)]

In [ ]:
def avg_shape(a,b, t):
    return np.array([((1-t) * i[0] + t * j[0],(1-t) * i[1] + t * j[1])  for i,j in zip(a,b)])


In [ ]:
# point5 = avg_shape(x2,y2, 0.5)

In [ ]:
# tri = Delaunay(point5)

In [ ]:
# t_simp = tri.simplices

In [ ]:
# triPoints = point5[t_simp]

In [ ]:
# xPoints = np.array(x2)[t_simp]

In [ ]:
# yPoints = np.array(y2)[t_simp]

In [ ]:
# This does the right thing

def get_basis(m_tri):
#     m_Tri is an array of 3 lists, each with x,y coords, then also add extrabrow and column to account for translatiom
    b1 = m_tri[2] - m_tri[0]
    b2 = m_tri[1] - m_tri[0]
    part_b =  np.stack((b1,b2,m_tri[0]),axis=-1)
    add_on = np.array([0,0,1])
    return np.stack((part_b[0],part_b[1], add_on), axis=0)

In [ ]:
# computer affine
# this computes the transformation from tri1 to tri2
def compute_affine(tri1, tri2):
    return get_basis(tri2).dot(np.linalg.inv(get_basis(tri1)))

In [147]:
def rng_tuple(z, z_max):
    rng = 5
    return (max(z-rng, 0) , min(z + rng, z_max - 1))    

def get_interp_vals(tg_tuple, src_im):
    x_b = math.floor(np.amin(tg_tuple[0]))
    x_e = math.floor(np.amax(tg_tuple[0]))
    y_b = math.floor(np.amin(tg_tuple[1]))
    y_e = math.floor(np.amax(tg_tuple[1]))
    xold = np.arange(x_b, x_e)
    yold = np.arange(y_b, y_e)
    src_im_inter = RectBivariateSpline(yold, xold, src_im[y_b: y_e,x_b: x_e])
    f = src_im_inter(tg_tuple[1], tg_tuple[0],grid=False)
    return f  


def merge_triangles(srcTriList, tgtTriList,src_im, frac = 0.5):
    new_im = np.zeros(np.shape(src_im))
    src_im_disp = np.dstack((src_im,src_im,src_im))
    for stri, ttri in zip(srcTriList, tgtTriList):
        height = len(src_im)
        width = len(src_im[0])
        stform = compute_affine(stri, ttri)
        r = [s[0] for s in ttri]
        c = [s[1] for s in ttri]
        rr, cc = polygon(r,c, shape=(width,height))
        new_coords = inv(stform).dot(np.array([rr,cc,np.ones(np.shape(rr))])).astype(int)
        new_im[cc,rr] = np.reshape(get_interp_vals(new_coords,src_im), np.shape(new_im[cc,rr]))
    return frac * new_im 
            

        

In [ ]:
# [im1_r, im1_g, im1_b] = np.dsplit(im1, 3)
# [im2_r, im2_g, im2_b] = np.dsplit(im2, 3)

In [ ]:

# newIm1_r  = merge_triangles(xPoints, triPoints, im1_r.astype(np.float32))
# newIm1_g  = merge_triangles(xPoints, triPoints, im1_g.astype(np.float32))
# newIm1_b  = merge_triangles(xPoints, triPoints, im1_b.astype(np.float32))


In [ ]:
# newIm2_r= merge_triangles(yPoints, triPoints, im2_r.astype(np.float32))
# newIm2_g= merge_triangles(yPoints, triPoints, im2_g.astype(np.float32))
# newIm2_b= merge_triangles(yPoints, triPoints, im2_b.astype(np.float32))


In [ ]:

# newIm3_r = newIm1_r + newIm2_r
# newIm3_g = newIm1_g + newIm2_g
# newIm3_b = newIm1_b + newIm2_b
# im1_n = np.dstack((newIm1_r, newIm1_g, newIm1_b)) 
# im2_n = np.dstack((newIm2_r, newIm2_g, newIm2_b)) 
# im3 = np.dstack((newIm3_r, newIm3_g, newIm3_b)) 


In [ ]:
# # first index is length, second is width
# # len(im2) is length and len(im2[0]) is width
# plt.imshow(im3)
# plt.show()



In [ ]:
# plt.imshow(im1)
# plt.show()


In [ ]:
# plt.imshow(im2)
# plt.show()

In [ ]:
def sc_disp(im_c, cover_x=[0], cover_y=[0]):
    im_c[cover_y, cover_x] = 1
    plt.imshow(np.dstack((im_c,im_c,im_c)))
    plt.show()

In [ ]:
# sc_disp(im1_r)

In [ ]:
# The idea is that we input two images. If we do not already have triangulation points,
# Then we plot our own. It might be better to keep plot function and the face function seperate, not sure. 
# Else, we would find triangulation,find avg triangles. 
# Then loop. 
# One function
# get x and y and transition stage triangles with simplices. 
# Ask how this works, do we always copy from two source images. 
# Merge faces 6 times, 3 for each image's channels. 
# Save each image. 

In [151]:
def morph(im1, im2, im1_pts, im2_pts, tri_simp, warp_frac, dissolve_frac, caricature=None):
    im1_tris = np.array(im1_pts)[tri_simp]
    im2_tris = np.array(im2_pts)[tri_simp]
    warp_pts = avg_shape(im1_pts,im2_pts, warp_frac)
    warp_tris = warp_pts[tri_simp]
    im1_ch = np.dsplit(im1, im1.shape[-1])
    im2_ch = np.dsplit(im2, im2.shape[-1])
#     merging 
    if (caricature):
        newIm1_ch = [merge_triangles(im1_tris, warp_tris, i.astype(np.float32), (1 + dissolve_frac)) for i in im1_ch]
        newIm2_ch = [merge_triangles(im2_tris, warp_tris, i.astype(np.float32), (-dissolve_frac)) for i in im2_ch]
    else:
        newIm1_ch = [merge_triangles(im1_tris, warp_tris, i.astype(np.float32), (1 - dissolve_frac)) for i in im1_ch]
        newIm2_ch = [merge_triangles(im2_tris, warp_tris, i.astype(np.float32), (dissolve_frac)) for i in im2_ch]
    im1_n = np.dstack(tuple(newIm1_ch))
    im2_n = np.dstack(tuple(newIm2_ch))

    morph_im = np.dstack(tuple([a + b for a,b in zip(newIm1_ch, newIm2_ch)])) 
#     plt.imshow(morph_im)
#     plt.show()
    return morph_im

In [ ]:
def give_tri(pts_a, pts_b):
    point5 = avg_shape(pts_a,pts_b, 0.5)
    return Delaunay(point5)

In [150]:



def create_morph(imname_a, imname_b, pts_a=None, pts_b=None, num_points = 36, resize=(750,602,3), num_frames=45, caricature=None):
    # high sf
    im2 = skio.imread(imname_b)/255
    im2 = sp.misc.imresize(im2, resize)/255
    # low sf
    im = skio.imread(imname_a)/255
#     reshape
    im1 = sp.misc.imresize(im, resize)/255
    print(np.shape(im1))

    
    
#     give points if not given already
    if ((pts_a == None) or (pts_b == None)):
        pts_a,pts_b = get_points(im1, im2, num_points)
#     add corners
        pts_a += [(0.0,0.0), (float(len(im2[0])),0), (float(len(im2[0])), float(len(im2))),(0.0, float(len(im2)))]
        pts_b += [(0.0,0.0), (float(len(im2[0])),0), (float(len(im2[0])), float(len(im2))),(0.0, float(len(im2)))]
    tri = give_tri(pts_a, pts_b)
    tri_simp = tri.simplices
#     we include 46 so we can have the number 45
# create 45 frames
#     save first image
    fname = 'merges/' + imname_a[:-4] + '_' + imname_b[:-4] + '_' + str(1000) + imname_b[-4:len(imname_b)]
    skio.imsave(fname, im1)
    for i in range(1,num_frames):
#         get the morphed image and save it somewhere. 
        increment = 1 / num_frames
        
        new_im = morph(im1, im2, pts_a, pts_b, tri_simp, i * increment, i * increment,caricature)

        fname = 'merges/' + imname_a[:-4] + '_' + imname_b[:-4] + '_' + str(1000 + i) + imname_b[-4:len(imname_b)]
        skio.imsave(fname, np.clip(new_im,0.0,1.0))
#     save last image
    fname = 'merges/' + imname_a[:-4] + '_' + imname_b[:-4] + '_' + str(1000 + num_frames) + imname_b[-4:len(imname_b)]
    skio.imsave(fname, im2)
    all_names = 'merges/' + imname_a[:-4] + '_' + imname_b[:-4] + '_*' + imname_b[-4:len(imname_b)]
    o_name = 'gifs/' + imname_a[:-4] + '_' + imname_b[:-4] + '_merge.gif'
    os.system('convert -delay 10 {0} {1}'.format(all_names, o_name))
    return pts_a, pts_b


In [ ]:
im2 = skio.imread('george_small.jpg')/255
x2 = [(54.37187119353564, 187.56292782514709), (114.84640326648253, 78.194093225136839), (222.92854569472797, 22.866329839249261), (382.47837499356655, 34.446559385132673), (458.39321312769135, 106.50132100396297), (491.84720959357679, 192.70969651220639), (135.43347801471975, 639.19188011460142), (72.385561598243214, 545.26335157576898), (58.23194770883012, 423.02759525811041), (71.098869426478387, 289.21160939456843), (119.99317195354183, 175.98269827926367), (219.06846917943352, 129.66178009572991), (360.60460807356452, 136.09524095455401), (446.81298358180783, 209.43669474514911), (476.40690353239887, 321.37891368868907), (490.56051742181199, 448.76143869340694), (454.53313661239685, 561.9903498087117), (379.90499065003684, 644.33864880166061), (249.94908130178936, 717.68010259225582), (85.25248331589151, 312.37206848633525), (145.72701538883837, 277.63137984868501), (229.36200655355213, 299.50514676868704), (347.7376863559162, 307.22529979927594), (395.34529671121476, 287.92491722280363), (463.53998181475066, 321.37891368868907), (171.4608588241349, 352.25952581104491), (376.04491413474244, 361.26637101339873), (202.34147094649074, 473.20858995693868), (278.25630908061555, 356.11960232633942), (341.30422549709209, 480.92874298752764), (280.8296934241452, 455.19489955223111), (184.32778054178317, 576.14396369812482), (269.24946387826174, 551.69681243459308), (350.31107069944591, 587.72419324400835), (310.42361337473619, 605.73788364871587), (237.0821595841411, 607.02457582048066)]
y2 = [(65.401792072157605, 180.16528771489618), (111.17846970262113, 60.637296124241402), (202.73182496354818, 9.7743209792819243), (379.48066359228233, 12.317469736529915), (455.77512630972149, 88.611932453969075), (535.88431216303275, 204.32520090875187), (190.01608117730834, 657.00567969889119), (123.89421348886103, 567.99547319521207), (109.90689532399713, 480.25684107015701), (97.191151537757293, 334.0257875283985), (137.88153165372486, 154.73380014241638), (239.60748194364382, 101.32767624020892), (379.48066359228233, 100.05610186158492), (465.94772133871345, 159.82009765691237), (493.92235766844112, 328.93949001390263), (493.92235766844112, 490.42943609914892), (473.57716761045731, 573.08177070970805), (415.08474619375397, 643.01836153402735), (296.82832898172319, 684.98031602861886), (121.35106473161304, 331.4826387711505), (167.12774236207653, 275.53336611169516), (259.95267200162755, 295.87855616967897), (359.13547353429851, 297.15013054830297), (429.07206435861781, 272.99021735444717), (468.49087009596144, 322.58161812078265), (200.18867620630019, 328.93949001390263), (398.55427927164214, 326.39634125665464), (243.42220507951575, 444.65275846868536), (298.09990336034718, 322.58161812078265), (347.69130412668267, 447.19590722593335), (294.2851802244752, 454.82535349767727), (210.36127123529209, 546.37870875860426), (289.19888270997933, 533.66296497236453), (379.48066359228233, 541.29241124410839), (346.41972974805867, 564.1807500593402), (287.92730833135533, 574.35334508833205)]
x2+= [(0.0,0.0), (float(len(im2[0])),0), (float(len(im2[0])), float(len(im2))),(0.0, float(len(im2)))]
y2+= [(0.0,0.0), (float(len(im2[0])),0), (float(len(im2[0])), float(len(im2))),(0.0, float(len(im2)))]

In [125]:

create_morph('eric_small.jpg', 'george_small.jpg', x2, y2)

0
43839
try 1
[[[ 0.99782135  0.99816993  0.99694989]
  [ 0.99782135  0.99816993  0.99694989]
  [ 0.99782135  0.99816993  0.99694989]
  ..., 
  [ 0.91494554  0.91572985  0.8682353 ]
  [ 0.91128541  0.91206972  0.86457517]
  [ 0.91128541  0.91206972  0.86457517]]

 [[ 0.99782135  0.99816993  0.99694989]
  [ 0.99782135  0.99816993  0.99694989]
  [ 0.99782135  0.99816993  0.99694989]
  ..., 
  [ 0.91494554  0.91572985  0.8682353 ]
  [ 0.91494554  0.91572985  0.8682353 ]
  [ 0.91511983  0.91590414  0.86840959]]

 [[ 0.99782135  0.99816993  0.99694989]
  [ 0.99782135  0.99816993  0.99694989]
  [ 0.99782135  0.99816993  0.99694989]
  ..., 
  [ 0.91494554  0.91572985  0.8682353 ]
  [ 0.91503268  0.915817    0.86832245]
  [ 0.91503268  0.915817    0.86832245]]

 ..., 
 [[ 0.07991286  0.09533769  0.10840959]
  [ 0.07180828  0.08723312  0.10030501]
  [ 0.07938998  0.09481482  0.10788671]
  ..., 
  [ 0.07102397  0.07860567  0.07616558]
  [ 0.07503268  0.08261438  0.08017429]
  [ 0.07102397  0.078

[[[ 0.98474946  0.98718954  0.97864924]
  [ 0.98474946  0.98718954  0.97864924]
  [ 0.98474946  0.98718954  0.97864924]
  ..., 
  [ 0.89873639  0.90422659  0.85411766]
  [ 0.89664489  0.90213508  0.85202615]
  [ 0.89664489  0.90213508  0.85202615]]

 [[ 0.98474946  0.98718954  0.97864924]
  [ 0.98474946  0.98718954  0.97864924]
  [ 0.98474946  0.98718954  0.97864924]
  ..., 
  [ 0.89873639  0.90422659  0.85411766]
  [ 0.89873639  0.90422659  0.85411766]
  [ 0.89995643  0.90544663  0.8553377 ]]

 [[ 0.98474946  0.98718954  0.97864924]
  [ 0.98474946  0.98718954  0.97864924]
  [ 0.98474946  0.98718954  0.97864924]
  ..., 
  [ 0.89873639  0.90422659  0.85411766]
  [ 0.89934641  0.90483661  0.85472768]
  [ 0.89934641  0.90483661  0.85472768]]

 ..., 
 [[ 0.08880175  0.10265795  0.12357299]
  [ 0.07912854  0.09298475  0.11389978]
  [ 0.08514161  0.09899782  0.11991286]
  ..., 
  [ 0.07363835  0.07965142  0.08610022]
  [ 0.07816994  0.08418301  0.09063181]
  [ 0.07363835  0.07965142  0.08610

[[[ 0.97167756  0.97620915  0.96034859]
  [ 0.97167756  0.97620915  0.96034859]
  [ 0.97167756  0.97620915  0.96034859]
  ..., 
  [ 0.88252724  0.89272332  0.84000001]
  [ 0.88200436  0.89220044  0.83947713]
  [ 0.88200436  0.89220044  0.83947713]]

 [[ 0.97167756  0.97620915  0.96034859]
  [ 0.97167756  0.97620915  0.96034859]
  [ 0.97167756  0.97620915  0.96034859]
  ..., 
  [ 0.88252724  0.89272332  0.84000001]
  [ 0.88252724  0.89272332  0.84000001]
  [ 0.88479304  0.89498911  0.8422658 ]]

 [[ 0.97167756  0.97620915  0.96034859]
  [ 0.97167756  0.97620915  0.96034859]
  [ 0.97167756  0.97620915  0.96034859]
  ..., 
  [ 0.88252724  0.89272332  0.84000001]
  [ 0.88366014  0.89385622  0.84113291]
  [ 0.88366014  0.89385622  0.84113291]]

 ..., 
 [[ 0.09542484  0.10771242  0.13647059]
  [ 0.08644881  0.09873639  0.12749456]
  [ 0.09089325  0.10318083  0.131939  ]
  ..., 
  [ 0.07625273  0.08069717  0.09603486]
  [ 0.08130719  0.08575164  0.10108933]
  [ 0.07625273  0.08069717  0.09603

KeyboardInterrupt: 

In [ ]:
im2 = skio.imread('daniel_lin.jpg')/255
im2 = sp.misc.imresize(im2, (750,602,3))/255
# low sf
im = skio.imread('daniel_liu.jpg')/255
#   reshape
im1 = sp.misc.imresize(im,(750,602,3) )/255
pts_a,pts_b = get_points(im1, im2, 36)
#     add corners
pts_a += [(0.0,0.0), (float(len(im2[0])),0), (float(len(im2[0])), float(len(im2))),(0.0, float(len(im2)))]
pts_b += [(0.0,0.0), (float(len(im2[0])),0), (float(len(im2[0])), float(len(im2))),(0.0, float(len(im2)))]


In [133]:
pts_c,pts_d = get_points(im1, im2, 23)
#     add corners
pts_c += [(0.0,0.0), (float(len(im2[0])),0), (float(len(im2[0])), float(len(im2))),(0.0, float(len(im2)))]
pts_d += [(0.0,0.0), (float(len(im2[0])),0), (float(len(im2[0])), float(len(im2))),(0.0, float(len(im2)))]


Please select 2 points in each image for alignment.


In [134]:
x3, y3 = create_morph('daniel_liu.jpg', 'daniel_lin.jpg',pts_c, pts_d, 36)

In [ ]:
# so do both daniels and then move on to the median faces

In [143]:
x4, y4 = create_morph('alexander_hamilton.png', 'thomas_jefferson.png',num_points=8)

(750, 602, 4)
Please select 2 points in each image for alignment.


[(365.43506493506476, 154.53246753246742),
 (184.83441558441547, 164.67857142857133),
 (138.16233766233751, 318.89935064935059),
 (401.96103896103881, 324.98701298701292),
 (314.70454545454533, 324.98701298701292),
 (397.90259740259722, 385.86363636363626),
 (403.99025974025966, 454.85714285714278),
 (339.05519480519462, 454.85714285714278),
 (0.0, 0.0),
 (602.0, 0),
 (602.0, 750.0),
 (0.0, 750.0)]

In [145]:
y4

[(401.96103896103881, 118.00649350649337),
 (227.44805194805184, 118.00649350649337),
 (144.24999999999983, 318.89935064935059),
 (436.45779220779212, 349.33766233766227),
 (359.34740259740244, 343.24999999999989),
 (422.25324675324663, 410.21428571428561),
 (424.28246753246736, 473.1201298701298),
 (363.40584415584402, 473.1201298701298),
 (0.0, 0.0),
 (602.0, 0),
 (602.0, 750.0),
 (0.0, 750.0)]